name: Refresh 2.0

on:
  schedule:
    - cron:  '0 3 * * *' # Runs every day at 3am

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ jorgeluis8ar.github.io }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ 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 }}
